<script>
	import {
		IconBook,
		IconAdd,
		IconEdit,
		IconArrowDown,
		IconArrowLeft,
		IconArrowRight,
		IconArrowUp,
		IconBox3d,
		IconCellSignal,
		IconHtml,
		IconCodeBranch,
		IconChartScatter,
		IconCircleInfo,
		IconClose,
		IconCode,
		IconDatabase,
		IconDelete,
		IconDocument,
		IconDocumentDownload,
		IconEject,
		IconEye,
		IconEyeClose,
		IconFavorite,
		IconFavoriteFill,
		IconFilterAlt,
		IconFlowerAlt,
		IconFolder,
		IconFullscreen,
		IconFullscreenAlt,
		IconFunnelAscending,
		IconFunnelDescending,
		IconGlobe,
		IconGradient,
		IconGrid,
		IconHandPointer,
		IconHashtag,
		IconHistory,
		IconInfinite,
		IconKeyboard,
		IconMap,
		IconMention,
		IconMoon,
		IconMouse,
		IconSun,
		IconMessageCircle,
		IconNextFill,
		IconMenu,
		IconOptionsHorizontal,
		IconOptionsVertical,
		IconOptionsVerticalEncircled,
		IconPalette,
		IconPause,
		IconPin,
		IconPlayFill,
		IconPreviousFill,
		IconRadio,
		IconRadioOn,
		IconRotate,
		IconSearch,
		IconSettings,
		IconSwitchAlt,
		IconShare,
		IconShuffle,
		IconSidebarFillRight,
		IconSignal,
		IconSort,
		IconSpeakers,
		IconSpeakersFill,
		IconSparkles,
		IconTag,
		IconTv,
		IconUnorderedList,
		IconUser,
		IconUsers,
		IconWifiOff,
		IconWifi
	} from 'obra-icons-svelte'
	import IconDeckPanel from '$lib/components/icon-deck-panel.svelte'

	/** @type {{icon: string, title?: string, class?: string, size?: string | number, children?: any, [key: string]: any}} */
	const {children, icon = '', title, class: className = '', size = 18, ...rest} = $props()

	const icons = {
		book: IconBook,
		add: IconAdd,
		edit: IconEdit,
		'arrow-down': IconArrowDown,
		'arrow-left': IconArrowLeft,
		'arrow-right': IconArrowRight,
		'arrow-up': IconArrowUp,
		'box-3d': IconBox3d,
		'chart-scatter': IconChartScatter,
		'circle-info': IconCircleInfo,
		'code-branch': IconCodeBranch,
		html: IconHtml,
		close: IconClose,
		code: IconCode,
		database: IconDatabase,
		delete: IconDelete,
		document: IconDocument,
		'document-download': IconDocumentDownload,
		eject: IconEject,
		eye: IconEye,
		'eye-close': IconEyeClose,
		favorite: IconFavorite,
		'favorite-fill': IconFavoriteFill,
		'filter-alt': IconFilterAlt,
		'flower-alt': IconFlowerAlt,
		folder: IconFolder,
		fullscreen: IconFullscreen,
		'fullscreen-alt': IconFullscreenAlt,
		'funnel-ascending': IconFunnelAscending,
		'funnel-descending': IconFunnelDescending,
		globe: IconGlobe,
		gradient: IconGradient,
		grid: IconGrid,
		'hand-pointer': IconHandPointer,
		hash: IconHashtag,
		hashtag: IconHashtag,
		history: IconHistory,
		infinite: IconInfinite,
		keyboard: IconKeyboard,
		map: IconMap,
		at: IconMention,
		mention: IconMention,
		mouse: IconMouse,
		'message-circle': IconMessageCircle,
		'next-fill': IconNextFill,
		menu: IconMenu,
		'options-horizontal': IconOptionsHorizontal,
		'options-vertical': IconOptionsVertical,
		'options-vertical-encircled': IconOptionsVerticalEncircled,
		palette: IconPalette,
		pause: IconPause,
		pin: IconPin,
		'play-fill': IconPlayFill,
		'previous-fill': IconPreviousFill,
		'cell-signal': IconCellSignal,
		radio: IconRadio,
		'radio-on': IconRadioOn,
		rotate: IconRotate,
		search: IconSearch,
		'switch-alt': IconSwitchAlt,
		moon: IconMoon,
		sun: IconSun,
		settings: IconSettings,
		share: IconShare,
		shuffle: IconShuffle,
		'sidebar-fill-right': IconSidebarFillRight,
		signal: IconSignal,
		sort: IconSort,
		speakers: IconSpeakers,
		'speakers-fill': IconSpeakersFill,
		sparkles: IconSparkles,
		tag: IconTag,
		tv: IconTv,
		'unordered-list': IconUnorderedList,
		user: IconUser,
		users: IconUsers,
		'wifi-off': IconWifiOff,
		wifi: IconWifi,
		'deck-panel': IconDeckPanel
	}

	const Icon = $derived(icons[icon] ?? null)
</script>

<i class={`icon ${className}`} class:icon {title}>
	{#if Icon}
		<Icon {size} {...rest} />
	{/if}
	{#if children}
		{@render children()}
	{/if}
</i>

<style>
	.icon {
		display: flex;
		align-items: center;
		gap: var(--space-1);
		font-style: normal;
	}
</style>
